### ISSUE TITLE
Resources: New templates of Chongqing Rail Transit

### ISSUE THREAD

**Issue by xiguagreen** [railmapgen/rmg-templates#231] opened 2023-04-08 03:12 UTC
**Justification:** 27号线

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="crt" line="cq27" major="false"><summary>crt/cq27</summary><details type="name">{"en":"Line 27&amp;Bitong Line","zh-Hans":"27号线/璧铜线","zh-Hant":"27號線/璧銅线","ko":"라인 27 / 바이 구리 와이어"}</details><details type="param">{"svgWidth":{"destination":2000,"runin":2000,"railmap":2000,"indoor":2000},"svg_height":400,"style":"shmetro","y_pc":50,"padding":10,"direction":"r","platform_num":"1","theme":["other","other","#f0c656","#fff"],"line_name":["27号线","Line 27"],"current_stn_idx":"BOCTGI","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["BOCTGI"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":200},"2uFYan":{"name":["沙坪坝","Shapingba"],"secondaryName":false,"num":"09","services":["local"],"parents":["A_eh8p"],"children":["erB2C1"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["chongqing","cq9","#862041","#fff","9号线","Line 9"],["chongqing","cq1","#E4002B","#fff","1号线","Line 1"],["chongqing","loop","#A89968","#fff","环线","Loop Line"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"erB2C1":{"name":["磁器口","Ciqikou"],"secondaryName":false,"num":"10","services":["local"],"parents":["2uFYan"],"children":["S14hDl"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["chongqing","cq1","#E4002B","#fff","1号线","Line 1"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["GXNWc6"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":200},"S14hDl":{"name":["西永","Xiyong"],"secondaryName":false,"num":"11","services":["local"],"parents":["erB2C1"],"children":["8Yucqk"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#81c1dd","#fff","7号线","Line 7"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"8Yucqk":{"name":["寨山坪","Zhaishanping"],"secondaryName":false,"num":"12","services":["local"],"parents":["S14hDl"],"children":["4Z2Cb0"],"branch":{"left":[],"right":[]},"transfer":{"info":[[],[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"4Z2Cb0":{"name":["大学城南","Daxuecheng South"],"secondaryName":false,"num":"13","services":["local"],"parents":["8Yucqk"],"children":["f5nmOk"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#9f9bb4","#fff","15号线","Line 15"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"f5nmOk":{"name":["虎溪","Huxi"],"secondaryName":false,"num":"14","services":["local"],"parents":["4Z2Cb0"],"children":["rK1Ijs"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#7bb678","#fff","17号线","Line 17"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"rK1Ijs":{"name":["璧山","Bishan"],"secondaryName":false,"num":"15","services":["local"],"parents":["f5nmOk"],"children":["ESu8Fs"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["chongqing","cq1","#E4002B","#fff","1号线","Line 1"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"ESu8Fs":{"name":["黛山大道","Daishan Avenue"],"secondaryName":false,"num":"16","services":["local"],"parents":["rK1Ijs"],"children":["XGtdfp"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"XGtdfp":{"name":["河边","Hebian"],"secondaryName":false,"num":"17","services":["local"],"parents":["ESu8Fs"],"children":["zMIG5y"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"zMIG5y":{"name":["青龙湖","Qinglonghu"],"secondaryName":false,"num":"18","services":["local"],"parents":["XGtdfp"],"children":["U9JLvX"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"U9JLvX":{"name":["大路","Dalu"],"secondaryName":false,"num":"19","services":["local"],"parents":["zMIG5y"],"children":["67gr7X"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"67gr7X":{"name":["蒲吕","Pulu"],"secondaryName":false,"num":"20","services":["local"],"parents":["U9JLvX"],"children":["kK1LUK"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"kK1LUK":{"name":["铜梁新城","Tongliang Xincheng"],"secondaryName":false,"num":"21","services":["local"],"parents":["67gr7X"],"children":["_i0ULk"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"_i0ULk":{"name":["铜梁","Tongliang"],"secondaryName":false,"num":"22","services":["local"],"parents":["kK1LUK"],"children":["GXNWc6"],"branch":{"left":[],"right":[]},"transfer":{"info":[[],[],[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"GXNWc6":{"name":["铜梁西","Tongliang West"],"secondaryName":false,"num":"23","services":["local"],"parents":["_i0ULk"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"BOCTGI":{"name":["惠民","Huimin"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["YVBXOZ"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"YVBXOZ":{"name":["重庆东站","Chongqing East Railway Station"],"secondaryName":false,"num":"02","services":["local"],"parents":["BOCTGI"],"children":["7fR4UC"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["chongqing","cq6","#F67599","#fff","6号线","Line 6"],["other","other","#376358","#fff","24号线","Line 24"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"7fR4UC":{"name":["广福大道","Guangfu Avenue"],"secondaryName":false,"num":"03","services":["local"],"parents":["YVBXOZ"],"children":["xwmoDj"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"xwmoDj":{"name":["南坪","Nanping"],"secondaryName":false,"num":"04","services":["local"],"parents":["7fR4UC"],"children":["sWpSdo"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["chongqing","cq3","#003DA5","#fff","3号线","Line 3"],["chongqing","cq10","#5F249F","#fff","10号线","Line 10"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"sWpSdo":{"name":["南滨路","Nanbinlu"],"secondaryName":false,"num":"05","services":["local"],"parents":["xwmoDj"],"children":["c6U5_C"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"c6U5_C":{"name":["重庆站"," Chongqing Railway Station"],"secondaryName":false,"num":"06","services":["local"],"parents":["sWpSdo"],"children":["29j2CC"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["chongqing","cq1","#E4002B","#fff","1号线","Line 1"]],[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"29j2CC":{"name":["大坪西","Daping West"],"secondaryName":false,"num":"07","services":["local"],"parents":["c6U5_C"],"children":["A_eh8p"],"branch":{"left":[],"right":[]},"transfer":{"info":[[],[["chongqing","cq18","#3cdbc0","#fff","18号线","Line 18"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"A_eh8p":{"name":["石桥铺","Shiqiaopu"],"secondaryName":false,"num":"08","services":["local"],"parents":["29j2CC"],"children":["2uFYan"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["chongqing","cq5","#00A3E0","#fff","5号线","Line 5"],["chongqing","cq1","#E4002B","#fff","1号线","Line 1"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"10","psd_num":"1","info_panel_type":"sh","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"branchSpacingPct":10}</details></details>

**Comment by 52PD** [comment] 2023-04-08 16:37
Closed as duplicate of #233 .

**Closed by 52PD** 2023-04-08 16:37 UTC
Labels: duplicate, resources
